### PR TITLE
Fix diagnostics messages (correct filename and output is cleared when compilation is successful)

### LINKED ISSUE #44: Error in file (not main)  shows in unrelated file
Well I have this piece of code that should error
no_errors

errors

I have an error in this other file where there should be none
note that the line and column are correct.
```
[{
	"resource": "/home/astrale/Coding/typst/typst-assignement-template/showcase.typ",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "unknown variable",
	"startLineNumber": 83,
	"startColumn": 48,
	"endLineNumber": 83,
	"endColumn": 49
}]```

### PR DESCRIPTION
**Pull request by Bramas**
fixes #44

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -289,21 +296,20 @@ impl Backend {
...
-                    })
-                    .collect(),
-                None,
-            )
-            .await;
+                    }],
+                    None,
+                )
+                .await;
+        }
```
Comment (nvarner) [inline src/main.rs:312]: Can we use something like [`join_all`](https://docs.rs/futures/latest/futures/future/fn.join_all.html) so we don't have to wait for each promise individually?

File: src/main.rs [hunk 2]
```diff
@@ -289,21 +296,20 @@ impl Backend {
...
-        self.client
-            .publish_diagnostics(
-                uri.clone(),
-                messages
-                    .into_iter()
-                    .map(|(message, range)| Diagnostic {
+        for (uri, message, range) in messages.into_iter() {
+            self.client
+                .publish_diagnostics(
+                    uri,
```
Comment (nvarner) [inline src/main.rs:302]: Can we merge diagnostics per URI so everything for each file is published at once? Otherwise, we may send diagnostics many times to the same file, which is both slow and will cause the last sent diagnostic to be overwritten each time.

Ideally, this would also handle the above added block to clear diagnostics by sending an empty set to files which we have checked but found no errors.

**Review by nvarner — CHANGES_REQUESTED** [review]

**Comment by nvarner** [comment]
Would also close #57

File: src/main.rs (hunk 2 above)
Comment (Bramas) [reply src/main.rs:302]: Yes I was thinking about it. First I thought that there was a single diagnostic per file but I did not realized that previous diagnostics were just overwritten.

I am fixing it now.

**Comment by Bramas** [comment]
I pushed a new version where diagnostics are grouped per file, and are sent together with join_all as suggested.

However I am unable to find a document where typst reports several errors, to try if it works as expected. Can typst return several error per file? it seems like it stops after the first error (hence always on a single file).

**Review by nvarner — APPROVED** [review]
A few things could be made more idiomatic. In general, it's better to avoid `mut` and instead build our collections from iterators. However, this looks pretty good, and I need to do some general refactoring anyway. If it turns out to be possible to make it nicer, that can be done then.
